blank_issues_enabled: false

contact_links:
  - name: Community Discussions
    url: https://github.com/Hrdtr/litetics/discussions
    about: Please ask and answer questions here.

  - name: 📚 Litetics Documentation
    url: https://github.com/Hrdtr/litetics#readme
    about: Check the documentation for usage of Litetics
